### ISSUE TITLE
GW Dataset

### ISSUE THREAD

**Issue by Aksei** [georgeretsi/pytorch-phocnet#6]
Hi, 
where did you download the GW dataset? Did you use images from the complete document (--> 20 pages) or did you used line images (as provided here http://www.fki.inf.unibe.ch/databases/iam-historical-document-database/washington-database).
I can't find a dataset online with an 'gtp' annotation file.
Thank you for you help.

**Comment by anofryev** [comment]
Same question. Can you give a reference to dataset that you used, please?

**Comment by georgeretsi** [comment]
Hi, I used the structure of GW given by Jon Almazan in the repo of PHOC attributes: https://github.com/almazan/watts. Specifically, the link to the dataset is https://www.dropbox.com/s/ewz5c2gmxwjyokm/GW.zip?dl=0.
